### ISSUE TITLE
ubuntu bionic running bats got an error: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by xiaozhu36** [cloudfoundry/bosh-acceptance-tests#45]
When I running bats based on ubuntu bionic release and got the following error:
```
Failures:

  1) network configuration when using manual networking deploys multiple manual networks
     Failure/Error: expect(bosh_ssh('batlight', 0, 'PATH=/sbin:/usr/sbin:$PATH; ifconfig', deployment: deployment.name).output).to include(static_ips[1])
     TypeError:
       no implicit conversion of nil into String
     # ./spec/system/network_configuration_spec.rb:79:in `block (3 levels) in <top (required)>'

Finished in 35 minutes 39 seconds (files took 0.41484 seconds to load)
72 examples, 1 failure, 12 pending

Failed examples:

rspec ./spec/system/network_configuration_spec.rb:73 # network configuration when using manual networking deploys multiple manual networks
```
This error did not happen in the ubuntu xenial release.

**Comment by StefanWutz** [comment]
Hi @xiaozhu36, can you provide us the bat.yml you are using for the tests on alicloud?

**Comment by xiaozhu36** [comment]
Hi @beyhan , this is my concourse ci yml : https://github.com/cloudfoundry-incubator/bosh-alicloud-light-stemcell-builder/blob/master/ci/pipeline.yml and please have a check.

**Comment by xiaozhu36** [comment]
@beyhan I am sorry for I gave an incorrect url. It should be in bionic branch:  https://github.com/cloudfoundry-incubator/bosh-alicloud-light-stemcell-builder/blob/bionic/ci/pipeline.yml. Please have a check again. Thanks.

**Comment by friegger** [comment]
@xiaozhu36 You need to specify a second static IP as described here: https://github.com/cloudfoundry/bosh-acceptance-tests#manual-networking as an example. Does your bat.yml provide this value?

**Comment by xiaozhu36** [comment]
@friegger Thanks for your idea. Actually, my bat.yml contains the second static ip and the following manifest in the bats ci test:
```
cpi: alicloud
properties:
  availability_zone: eu-central-1a
  instances: 1
  key_name: ubuntu-bionic-stemcell-bats
  networks:
  - cidr: 172.16.0.0/16
    gateway: 172.16.0.1
    name: default
    reserved: &1
    - 172.16.0.2-172.16.0.9
    security_groups: sg-gw82zcskkc64meo86g2i
    static: &2
    - 172.16.0.10-172.16.0.30
    static_ip: 172.16.0.29
    subnet: vsw-gw8ngzhj0afsqtg5m1ybu
    type: manual
  pool_size: 1
  second_static_ip: 172.16.0.30
  stemcell:
    name: bosh-alicloud-kvm-ubuntu-bionic-go_agent
    version: latest
  vip: 8.209.77.110
  batlight:
    missing: nope
  dns:
  - 47.91.79.69
  job_networks:
  - cidr: 172.16.0.0/16
    gateway: 172.16.0.1
    name: default
    reserved: *1
    security_groups: sg-gw82zcskkc64meo86g2i
    static: *2
    static_ip: 172.16.0.29
    subnet: vsw-gw8ngzhj0afsqtg5m1ybu
    type: manual
  use_static_ip: true
  use_vip: true
```

**Comment by xiaozhu36** [comment]
HI. @friegger It seems like the second_static_ip is not effect in my bats:
```
Generating deployment manifest with input:
---
cpi: alicloud
properties:
  availability_zone: eu-central-1a
  instances: 1
  key_name: ubuntu-bionic-stemcell-bats
  networks:
  - cidr: 172.16.0.0/16
    gateway: 172.16.0.1
    name: default
    reserved: &1
    - 172.16.0.2-172.16.0.9
    security_groups: sg-gw81s8yaxq49lumvnuum
    static: &2
    - 172.16.0.10-172.16.0.30
    static_ip: 172.16.0.29
    subnet: vsw-gw8rk6f7wx9d4kng72nu7
    type: manual
  pool_size: 1
  second_static_ip: 172.16.0.30
  stemcell:
    name: bosh-alicloud-kvm-ubuntu-bionic-go_agent
    version: latest
  vip: 47.91.92.24
  batlight:
    missing: nope
  dns:
  - 47.91.77.172
  job_networks:
  - cidr: 172.16.0.0/16
    gateway: 172.16.0.1
    name: default
    reserved: *1
    security_groups: sg-gw81s8yaxq49lumvnuum
    static: *2
    static_ip: 172.16.0.29
    subnet: vsw-gw8rk6f7wx9d4kng72nu7
    type: manual
  use_static_ip: true
  use_vip: true
Generated deployment manifest:
---
name: bat
releases:
- name: bat
  version: latest
update:
  canaries: 1
  canary_watch_time: 3000-90000
  update_watch_time: 3000-90000
  max_in_flight: 1
stemcells:
- alias: default
  name: bosh-alicloud-kvm-ubuntu-bionic-go_agent
  version: latest
instance_groups:
- name: batlight
  azs:
  - z1
  jobs:
  - name: batlight
    release: bat
    properties:
      batlight:
        missing: nope
  instances: 1
  stemcell: default
  networks:
  - name: default
    default:
    - dns
    - gateway
    static_ips:
    - 172.16.0.29
  - name: static
    static_ips:
    - 47.91.92.24
  vm_type: default
I, [2020-12-01T11:22:09.155840 #112]  INFO -- : Running bosh command --> /usr/local/bin/bosh --non-interactive --json -d bat deploy /tmp/d20201201-112-xv859x/deployment 2>&1
I, [2020-12-01T11:23:49.197260 #112]  INFO -- : {
    "Tables": null,
    "Blocks": [
        "\nTask 11 | 11:22:12 | ",
        "Preparing deployment: Preparing deployment",
        " (00:00:00)",
        "\nTask 11 | 11:22:12 | ",
        "Preparing deployment: Rendering templates",
        " (00:00:00)",
        "\nTask 11 | 11:22:12 | ",
        "Preparing package compilation: Finding packages to compile",
        " (00:00:00)",
        "\nTask 11 | 11:22:12 | ",
        "Updating instance batlight: batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48 (0) (canary)",
        "\nTask 11 | 11:22:12 | ",
        "L executing pre-stop: batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48 (0) (canary)",
        "\nTask 11 | 11:22:12 | ",
        "L executing drain: batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48 (0) (canary)",
        "\nTask 11 | 11:22:15 | ",
        "L stopping jobs: batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48 (0) (canary)",
        "\nTask 11 | 11:22:16 | ",
        "L executing post-stop: batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48 (0) (canary)",
        "\nTask 11 | 11:23:41 | ",
        "L installing packages: batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48 (0) (canary)",
        "\nTask 11 | 11:23:42 | ",
        "L configuring jobs: batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48 (0) (canary)",
        "\nTask 11 | 11:23:42 | ",
        "L executing pre-start: batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48 (0) (canary)",
        "\nTask 11 | 11:23:43 | ",
        "L starting jobs: batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48 (0) (canary)",
        "\nTask 11 | 11:23:47 | ",
        "L executing post-start: batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48 (0) (canary)",
        " (00:01:35)"
    ],
    "Lines": [
        "Using environment '47.91.77.172' as client 'admin'",
        "Using deployment 'bat'",
        "  instance_groups:\n",
        "  - name: batlight\n",
        "    networks:\n",
        "    - name: default\n",
        "      static_ips:\n",
        "+     - 172.16.0.29\n",
        "-     - 172.16.0.30\n",
        "Task 11",
        "\n",
        "\n\nTask 11 Started  Tue Dec  1 11:22:12 UTC 2020\nTask 11 Finished Tue Dec  1 11:23:47 UTC 2020\nTask 11 Duration 00:01:35",
        "\nTask 11 done\n",
        "Succeeded"
    ]
}
I, [2020-12-01T11:23:49.197717 #112]  INFO -- : Running bosh command --> /usr/local/bin/bosh --non-interactive --deployment bat ssh batlight/0 -c 'PATH=/sbin:/usr/sbin:$PATH; ifconfig'  2>&1
I, [2020-12-01T11:23:59.446303 #112]  INFO -- : batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stderr | Warning: Permanently added '47.91.77.172' (ECDSA) to the list of known hosts.
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stderr | Unauthorized use is strictly prohibited. All access and activity
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stderr | is subject to logging and monitoring.
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stderr | Unauthorized use is strictly prohibited. All access and activity
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stderr | is subject to logging and monitoring.
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout | eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         inet 172.16.0.29  netmask 255.255.0.0  broadcast 172.16.255.255
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         inet6 fe80::216:3eff:fe00:f247  prefixlen 64  scopeid 0x20<link>
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         ether 00:16:3e:00:f2:47  txqueuelen 1000  (Ethernet)
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         RX packets 311  bytes 77215 (77.2 KB)
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         RX errors 0  dropped 0  overruns 0  frame 0
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         TX packets 364  bytes 44233 (44.2 KB)
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout | 
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout | lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         inet 127.0.0.1  netmask 255.0.0.0
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         loop  txqueuelen 1000  (Local Loopback)
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         RX packets 2490  bytes 223387 (223.3 KB)
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         RX errors 0  dropped 0  overruns 0  frame 0
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         TX packets 2490  bytes 223387 (223.3 KB)
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout | 
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stderr | Connection to 172.16.0.29 closed.

I, [2020-12-01T11:23:59.446562 #112]  INFO -- : Running bosh command --> /usr/local/bin/bosh --non-interactive --deployment bat ssh batlight/0 -c 'PATH=/sbin:/usr/sbin:$PATH; ifconfig'  2>&1
I, [2020-12-01T11:24:09.794498 #112]  INFO -- : batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stderr | Warning: Permanently added '47.91.77.172' (ECDSA) to the list of known hosts.
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stderr | Unauthorized use is strictly prohibited. All access and activity
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stderr | is subject to logging and monitoring.
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stderr | Unauthorized use is strictly prohibited. All access and activity
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stderr | is subject to logging and monitoring.
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stderr | Connection to 172.16.0.29 closed.
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout | eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         inet 172.16.0.29  netmask 255.255.0.0  broadcast 172.16.255.255
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         inet6 fe80::216:3eff:fe00:f247  prefixlen 64  scopeid 0x20<link>
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         ether 00:16:3e:00:f2:47  txqueuelen 1000  (Ethernet)
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         RX packets 356  bytes 84538 (84.5 KB)
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         RX errors 0  dropped 0  overruns 0  frame 0
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         TX packets 404  bytes 51410 (51.4 KB)
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout | 
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout | lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         inet 127.0.0.1  netmask 255.0.0.0
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         loop  txqueuelen 1000  (Local Loopback)
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         RX packets 2490  bytes 223387 (223.3 KB)
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         RX errors 0  dropped 0  overruns 0  frame 0
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         TX packets 2490  bytes 223387 (223.3 KB)
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout |         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
batlight/8f48f693-589e-4df8-8be7-b3e63cc69f48: stdout | 

BATs example failed  'network configuration when using manual networking deploys multiple manual networks' ./spec/system/network_configuration_spec.rb:73 

  1) network configuration when using manual networking deploys multiple manual networks
     Failure/Error: expect(bosh_ssh('batlight', 0, 'PATH=/sbin:/usr/sbin:$PATH; ifconfig', deployment: deployment.name).output).to include(static_ips[1])
     TypeError:
       no implicit conversion of nil into String
     # ./spec/system/network_configuration_spec.rb:79:in `block (3 levels) in <top (required)>'
```

**Comment by StefanWutz** [comment]
Hi @xiaozhu36, the property _second_static_ip_ defines a secondary private ip address on the first NIC. What you need is a second network block which defines the second NIC. Something like this:
```
networks:
...
 - cidr: 172.16.1.0/16
    gateway: 172.16.1.1
    name: second
    reserved: &1
    - 172.16.1.2-172.16.1.9
    security_groups: sg-gw82zcskkc64meo86g2i
    static: &2
    - 172.16.1.10-172.16.1.30
    static_ip: 172.16.1.29   # this is the ip address assigned to the secondary nic
    subnet: vsw-gw8ngzhj0afsqtg5m1ybu
    type: manual
...
```
Have a look at https://github.com/cloudfoundry/bosh-acceptance-tests#manual-networking-1 for more details.

**Comment by StefanWutz** [comment]
@xiaozhu36 As discussed, the acceptance tests for aws also support multiple network configurations, see https://github.com/cloudfoundry/bosh-acceptance-tests/blob/master/templates/cloud_config_aws.yml.erb#L10. The related tests are also not disabled using '--tag ~multiple_manual_networks'.

Can you test again using a second network block as described in my previous comment?

**Comment by xiaozhu36** [comment]
Hi @StefanWutz Thanks for your advise. This issue has been fixed by adding `-tag ~multiple_manual_networks`.
